# Generated by Django 5.0.6 on 2026-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='instance_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
