# Generated by Django 5.0.6 on 2026-06-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('mensagem_override', models.TextField(blank=True, default='')),
                ('tipo_override', models.CharField(blank=True, default='texto', max_length=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviando', 'Enviando'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('enviados', models.IntegerField(default=0)),
                ('falhas', models.IntegerField(default=0)),
                ('pulados', models.IntegerField(default=0)),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instancias', models.ManyToManyField(blank=True, to='dispositivos.dispositivo')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.modelo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContatoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou'), ('pulado', 'Pulado')], default='pendente', max_length=20)),
                ('instancia', models.CharField(blank=True, default='', max_length=100)),
                ('erro', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='campanhas.campanha')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
